### ISSUE TITLE
Broken operator rendering

### ISSUE THREAD

**Issue by demensky** [timdp/swirly#36]
Code example:

```
-1-2-3-4-5-|

> tmp(()=>`--|`)
```

The operator is rendered empty (in SVG also):

![diagram](https://user-images.githubusercontent.com/10235949/176778178-883dbf61-ccee-44b0-be6a-7d7b53eaf3e6.png)

---

Code example (spaces around ` => `):

```
-1-2-3-4-5-|

> tmp(()=>`--|`)
```

SVG becomes invalid:

<img width="908" alt="Снимок экрана 2022-07-01 в 00 06 30" src="https://user-images.githubusercontent.com/10235949/176778346-a67b377a-57f5-48c0-9025-f6428556b36e.png">

--- 

Can be reproduced at https://swirly.dev/.

**Comment by timdp** [comment]
Odd, it works for me.

`&nbsp;` is a non-breaking space. Swirly replaces regular spaces with non-breaking ones so spaces around observables don't get collapsed. However, it should insert the literal character rather than the named entity code.

This might be browser-specific. I'll experiment with it tomorrow. I might use `<pre>` instead, so the non-breaking spaces aren't necessary.

**Comment by demensky** [comment]
I described incorrectly. This problem appears while downloading.

**Comment by timdp** [comment]
Ah, interesting. I'll look into it.

**Comment by demensky** [comment]
https://user-images.githubusercontent.com/10235949/176781027-2877782b-2938-47b7-a435-1f58cc90c0ad.mov

**Comment by timdp** [comment]
This should now be fixed on swirly.dev!
